version: 2

before:
  hooks:
    - go generate ./...
    - go mod tidy
    - go mod download
    - pandoc -s -t man assets/man/fox.md -o fox.1
    - pandoc -s -t man assets/man/fox-cat.md -o fox-cat.1
    - pandoc -s -t man assets/man/fox-hex.md -o fox-hex.1
    - pandoc -s -t man assets/man/fox-text.md -o fox-text.1
    - pandoc -s -t man assets/man/fox-hash.md -o fox-hash.1
    - pandoc -s -t man assets/man/fox-stat.md -o fox-stat.1
    - pandoc -s -t man assets/man/fox-dump.md -o fox-dump.1
    - pandoc -s -t man assets/man/fox-test.md -o fox-test.1
    - pandoc -s -t man assets/man/fox-hunt.md -o fox-hunt.1

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - fox.1
      - fox-cat.1
      - fox-hex.1
      - fox-text.1
      - fox-hash.1
      - fox-stat.1
      - fox-dump.1
      - fox-test.1
      - fox-hunt.1
      - README.md
      - LICENSE.md
      - SECURITY.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --yes
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: checksum

nfpms:
  - vendor: fox
    homepage: https://foxhunt.dev
    maintainer: Christian Uhsat <christian@uhsat.de>
    description: The Forensic Examiners Swiss Army Knife.
    license: GPL-3.0
    file_name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - archlinux
      - apk
      - deb
      - rpm
    provides:
      - fox
    section: utils
    contents:
      - src: ./LICENSE.md
        dst: /usr/share/doc/fox/copyright
        file_info:
          mode: 0644
      - src: ./fox.1
        dst: /usr/share/man/man1/fox.1
        file_info:
          mode: 0644
      - src: ./fox-cat.1
        dst: /usr/share/man/man1/fox-cat.1
        file_info:
          mode: 0644
      - src: ./fox-hex.1
        dst: /usr/share/man/man1/fox-hex.1
        file_info:
          mode: 0644
      - src: ./fox-text.1
        dst: /usr/share/man/man1/fox-text.1
        file_info:
          mode: 0644
      - src: ./fox-hash.1
        dst: /usr/share/man/man1/fox-hash.1
        file_info:
          mode: 0644
      - src: ./fox-stat.1
        dst: /usr/share/man/man1/fox-stat.1
        file_info:
          mode: 0644
      - src: ./fox-dump.1
        dst: /usr/share/man/man1/fox-dump.1
        file_info:
          mode: 0644
      - src: ./fox-test.1
        dst: /usr/share/man/man1/fox-test.1
        file_info:
          mode: 0644
      - src: ./fox-hunt.1
        dst: /usr/share/man/man1/fox-hunt.1
        file_info:
          mode: 0644

homebrew_casks:
  - url:
      verified: github.com/cuhsat/homebrew-fox/
    name: "fox"
    description: "The Forensic Examiners Swiss Army Knife"
    homepage: "https://foxhunt.dev/"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: cuhsat
      name: homebrew-fox
      branch: main
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
          end
    directory: Casks
    license: GPL-3.0
    manpages:
      - fox.1
      - fox-cat.1
      - fox-hex.1
      - fox-text.1
      - fox-hash.1
      - fox-stat.1
      - fox-dump.1
      - fox-test.1
      - fox-hunt.1
