name: Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v4
        with:
          install-only: true
      - name: Setup Syft
        uses: anchore/sbom-action/download-syft@v0
      - name: Setup Cosign
        uses: sigstore/cosign-installer@v3
      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1
      - name: Setup Go
        uses: actions/setup-go@v6
      - name: Setup GoVersionInfo
        run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
